### ISSUE TITLE
The MTU of OVS patch is shown as 0

### ISSUE THREAD

**Issue by cathay4t** [nmstate/nmstate#1195]
```yml
- name: patch1
  type: ovs-interface
  state: up
  ipv4:
    enabled: false
  ipv6:
    enabled: false
  lldp:
    enabled: false
  mtu: 0
  patch:
    peer: patch0
```
