### ISSUE TITLE
Clean up the OVS proxy profile after detaching a OVS system interface.

### ISSUE THREAD

**Issue by cathay4t** [nmstate/nmstate#1284]
```yaml
---
interfaces:
- name: eth1
  type: ethernet
  state: up
- name: br0
  type: ovs-bridge
  state: up
  bridge:
    port:
    - name: ovs0
    - name: eth1
```

```yaml
---
interfaces:
- name: br0
  type: ovs-bridge
  state: up
  bridge:
    port:
    - name: ovs0
```

After that 

```
[fge@el8 ovs]$ nmcli c
NAME           UUID                                  TYPE           DEVICE
enp1s0         c9c2833d-4436-4c5b-ba26-41b3001c9e85  ethernet       enp1s0
ovs0           b69d1d02-d5ec-4601-beda-3dc4ad0f0d7f  ovs-interface  ovs0
br0            750116e2-289d-4f28-9c2e-de0076b30f25  ovs-bridge     br0
eth1           9c5e0da0-4964-4f7e-a157-d6dd762527f7  ethernet       eth1
ovs-port-eth1  0dff8196-1722-4052-bc7a-21bb0c4b3de1  ovs-port       ovs-port-eth1
ovs-port-ovs0  6c7b8b0c-3050-4f2a-9a1a-9ab4e2b9587d  ovs-port       ovs-port-ovs0
```
