### ISSUE TITLE
Cannot revert SRIOV VF settings to default.

### ISSUE THREAD

**Issue by cathay4t** [nmstate/nmstate#1454]
When applying below state, got failure `NmstateVerificationError`

```yaml
---
interfaces:
  - name: ens1f1
    type: ethernet
    state: up
    ethernet:
     sr-iov:
       total-vfs: 2
       vfs: []
```

The expectation of this desire state should be revert all VF settings back to default.
