### ISSUE TITLE
Failure when setting veth peer as Ethernet.

### ISSUE THREAD

**Issue by cathay4t** [nmstate/nmstate#1461]
```yaml
---
interfaces:
- name: veth1
  type: veth
  state: up
  veth:
    peer: veth2
- name: veth2
  type: ethernet
  state: up
```

Error:

```
libnmstate.error.NmstateLibnmError: Activate profile
uuid:204dd312-6d6f-4dea-81fe-4482dcb49c10 iface:veth2 type: ethernet failed:
error=nm-manager-error-quark: No suitable device found for this connection
(device enp1s0 not available because profile is not compatible with device
(mismatching interface name)). (3)
```
