### ISSUE TITLE
nmstate ethtool ring settings

### ISSUE THREAD

**Issue by nmathew** [nmstate/nmstate#1759]
## Describe the bug
I am trying out ethtool changes.

https://github.com/nmstate/nmstate/commit/1ea97bfddc26b11887bf4e1e6368f3e122c5c664?diff=split

```
interfaces:
  - name: enpXXX
    state: up
    mtu: 1500
    ethtool:
      ring:
        rx: 2048
        rx-jumbo: 0
        rx-mini: 0
        tx: 512
```

Driver for this NIC is ixgbe

I have set rx-jumbo and rx-mini as 0, since most of the drivers don’t support it.

But what happens is 
 
![rpviewer(5)](https://user-images.githubusercontent.com/303523/146354985-5a857dc0-5818-4ce2-9026-9f7e76f4d680.png)

Any idea why  the values coming as “???”.

## Nmstate version
- 1.1.0

## NetworkManager version
- 1.32.12, nispor 1.2.0

## Platform
- sles15 sp2

## How reproducible
- 100%

## Steps to Reproduce
nmstatectl apply <nmstate-netcfg.yaml>

**Comment by ffmancera** [comment]
No idea. Let me try with a NIC with ixgbe. Thank for reporting.

**Comment by nmathew** [comment]
For getting the logs in /var/log/NetworkManager, enable the logging with
`nmcli general logging level TRACE domains ALL`

**Comment by nmathew** [comment]
`
diff --git a/src/libnm-platform/nm-platform-utils.c b/src/libnm-platform/nm-platform-utils.c

    `-        .rx_jumbo_pending = ring->rx_jumbo_pending,`
    `-        .rx_mini_pending  = ring->rx_mini_pending,`
  ` +        .rx_jumbo_pending = 0,`
   `+        .rx_mini_pending  = 0,`

`

**Comment by nmathew** [comment]
@ffmancera @cathay4t 

As Gris mentioned 
"???" coming is a cosmetic bug, he raised a bug for that https://bugzilla.redhat.com/show_bug.cgi?id=2034086.

He was able to set the ethtool setting for a dummy interface using below settings

Steps to Reproduce:
1. Enable trace logging of NetworkManager
2. sudo nmcli c add type dummy ifname dummy0 ethtool.ring-rx-mini 0
3. sudo journalctl  |grep ring-rx

this works for me also..

But the issue happens if you apply ethtool setting for a existing interface

steps for dummy:
Create an interface using below config
```
interfaces:
- name: dummy-dummy0
  state: up
  type: dummy
```

Then apply ethtool settings using
```
interfaces:
- name: dummy-dummy0
  state: up
  type: dummy
  ethtool:
    ring:
      rx: 256
      rx-jumbo: 0
      rx-mini: 0
      tx: 256
```

this time you will get an error like:

`2021-12-22 06:16:33,671 root         DEBUG    Device reapply failed on dummy-dummy0 dummy: error=nm-device-error-quark: Can't reapply any changes to 'ethtool' setting (3), Fallback to device activation`

This same error happens for me also, as I configure the NIC interface:

```
cat test-nmstate-netcfg
interfaces:
    - name: enp94s0f1
      state: up
      type: ethernet
      mtu: 1500
      ethtool:
        ring:
            rx: 2048
            rx-jumbo: 0
            rx-mini: 0
            tx: 512
```
 
nmstatectl apply log:

```
2021-12-22 03:57:35,378 root         DEBUG    Async action: Update profile uuid:dd9f3585-207b-4b81-b19d-b800b6f54c35 iface:enp94s0f1 type:ethernet started
2021-12-22 03:57:35,388 root         DEBUG    Async action: Update profile uuid:dd9f3585-207b-4b81-b19d-b800b6f54c35 iface:enp94s0f1 type:ethernet finished
2021-12-22 03:57:35,389 root         DEBUG    Async action: Reapply device config: enp94s0f1 ethernet dd9f3585-207b-4b81-b19d-b800b6f54c35 started


2021-12-22 03:57:35,393 root         DEBUG    Device reapply failed on enp94s0f1 ethernet: error=nm-device-error-quark: Can't reapply any changes to 'ethtool' setting (3), Fallback to device activation


2021-12-22 03:57:35,394 root         DEBUG    Async action: Activate profile uuid:dd9f3585-207b-4b81-b19d-b800b6f54c35 iface:enp94s0f1 type: ethernet started
2021-12-22 03:57:35,398 root         DEBUG    Connection activation initiated: iface=enp94s0f1 type=ethernet con-state=<enum NM_ACTIVE_CONNECTION_STATE_ACTIVATING of type NM.ActiveConnectionState>
2021-12-22 03:57:35,512 root         DEBUG    Connection activation succeeded: iface=enp94s0f1, type=ethernet, con_state=<enum NM_ACTIVE_CONNECTION_STATE_ACTIVATED of type NM.ActiveConnectionState>, dev_state=<enum NM_DEVICE_STATE_ACTIVATED of type NM.DeviceState>, state_flags=<flags NM_ACTIVATION_STATE_FLAG_LAYER2_READY | NM_ACTIVATION_STATE_FLAG_IP4_READY | NM_ACTIVATION_STATE_FLAG_IP6_READY of type NM.ActivationStateFlags>
2021-12-22 03:57:35,512 root         DEBUG    Async action: Activate profile uuid:dd9f3585-207b-4b81-b19d-b800b6f54c35 iface:enp94s0f1 type: ethernet finished
2021-12-22 03:57:35,527 root         DEBUG    Async action: Retrieve applied config: bridge docker0 started
```

In /var/log/NetworkManager:
```

2021-12-22T03:57:35.394341+00:00 localhost NetworkManager[23130]: <trace> [1640145455.3920] auth: call[186]: completed: authorized=1, challenge=0 (simulated)
2021-12-22T03:57:35.394685+00:00 localhost NetworkManager[23130]: <info>  [1640145455.3930] audit: op="device-reapply" interface="enp94s0f1" ifindex=4 args="ethtool.ring-rx-mini,ethtool.ring-tx,ethtool.ring-rx-jumbo,ethtool.ring-rx" pid=30391 uid=0 result="fail" reason="Can't reapply any changes to 'ethtool' setting"
```

**Comment by ffmancera** [comment]
Beniamino already created a MR for this on NM: https://gitlab.freedesktop.org/NetworkManager/NetworkManager/-/merge_requests/1051

**Comment by nmathew** [comment]
@ffmancera 

Will this patch fix the "reapply" issue also?

**Comment by ffmancera** [comment]
@nmathew About the reapply issue I think that is not possible because ethtool is one of the settings that NM cannot reapply. If I am not wrong, the interface must be down in order to modify ethtool settings.. therefore NM won't be able to use reapply.

Did you expect to be able to use reapply for ethtool properties? Is this possible in any other tool?

**Comment by ffmancera** [comment]
Patch merged on NM: https://gitlab.freedesktop.org/NetworkManager/NetworkManager/-/commit/e6bd98cc07dc76638c6d93e45508f04801e2c108

**Comment by nmathew** [comment]
@ffmancera 
```
# cat /proc/net/bonding/bond_data
Ethernet Channel Bonding Driver: v3.7.1 (April 27, 2011)

Bonding Mode: IEEE 802.3ad Dynamic link aggregation
Transmit Hash Policy: layer3+4 (1)
MII Status: up
MII Polling Interval (ms): 100
Up Delay (ms): 0
Down Delay (ms): 0
Peer Notification Delay (ms): 0

802.3ad info
LACP rate: fast
Min links: 0
Aggregator selection policy (ad_select): stable
System priority: 65535
System MAC address: 40:a6:b7:08:9b:00
Active Aggregator Info:
        Aggregator ID: 3
        Number of ports: 2
        Actor Key: 21
        Partner Key: 4007
        Partner Mac Address: 01:80:c2:00:00:01

Slave Interface: enp59s0f0
MII Status: up
Speed: 25000 Mbps
Duplex: full
Link Failure Count: 0
Permanent HW addr: 40:a6:b7:08:9b:00
Slave queue ID: 0
Aggregator ID: 3
Actor Churn State: none
Partner Churn State: none
Actor Churned Count: 0
Partner Churned Count: 0
details actor lacp pdu:
    system priority: 65535
    system mac address: 40:a6:b7:08:9b:00
    port key: 21
    port priority: 255
    port number: 1
    port state: 63
details partner lacp pdu:
    system priority: 32768
    system mac address: 01:80:c2:00:00:01
    oper key: 4007
    port priority: 32768
    port number: 55
    port state: 63

Slave Interface: enp59s0f1
MII Status: up
Speed: 25000 Mbps
Duplex: full
Link Failure Count: 0
Permanent HW addr: 40:a6:b7:08:9b:01
Slave queue ID: 0
Aggregator ID: 3
Actor Churn State: none
Partner Churn State: none
Actor Churned Count: 0
Partner Churned Count: 0
details actor lacp pdu:
    system priority: 65535
    system mac address: 40:a6:b7:08:9b:00
    port key: 21
    port priority: 255
    port number: 2
    port state: 63
details partner lacp pdu:
    system priority: 32768
    system mac address: 01:80:c2:00:00:01
    oper key: 4007
    port priority: 32768
    port number: 8247
    port state: 63


# ip  a
<showing only relevant onces>
3: enp59s0f0: <BROADCAST,MULTICAST,SLAVE,UP,LOWER_UP> mtu 9000 qdisc mq master bond_data state UP group default qlen 1000
    link/ether 40:a6:b7:08:9b:00 brd ff:ff:ff:ff:ff:ff

5: enp59s0f1: <BROADCAST,MULTICAST,SLAVE,UP,LOWER_UP> mtu 9000 qdisc mq master bond_data state UP group default qlen 1000
    link/ether 40:a6:b7:08:9b:00 brd ff:ff:ff:ff:ff:ff

13: bond_data: <BROADCAST,MULTICAST,MASTER,UP,LOWER_UP> mtu 9000 qdisc noqueue master ovs-system state UP group default qlen 1000
    link/ether 40:a6:b7:08:9b:00 brd ff:ff:ff:ff:ff:ff

# ethtool -g enp59s0f1
Ring parameters for enp59s0f1:
Pre-set maximums:
RX:             4096
RX Mini:        0
RX Jumbo:       0
TX:             4096
Current hardware settings:
RX:             512
RX Mini:        0
RX Jumbo:       0
TX:             512

# ethtool -G enp59s0f1 rx 4096 tx 4096

# ethtool -g enp59s0f1
Ring parameters for enp59s0f1:
Pre-set maximums:
RX:             4096
RX Mini:        0
RX Jumbo:       0
TX:             4096
Current hardware settings:
RX:             4096
RX Mini:        0
RX Jumbo:       0
TX:             4096

# ethtool -G enp59s0f1 rx 512 tx 512

# ethtool -g enp59s0f1
Ring parameters for enp59s0f1:
Pre-set maximums:
RX:             4096
RX Mini:        0
RX Jumbo:       0
TX:             4096
Current hardware settings:
RX:             512
RX Mini:        0
RX Jumbo:       0
TX:             512
```


So I think ethtool allows us to modify the ring settings while interface is UP, I don't know whether it internally brings down and brings up.  

What is the exact meaning of "reapply", just curious.

What I am doing is simple, I am trying to bring up one kubernetes CAPI based worker node, before the "kubeadm init", I am applying the nmstate network config.

```
          - name: bond_data
            type: bond
            state: up
            ipv4:
              dhcp: false
              enabled: false
            link-aggregation:
              options:
                 miimon: "100"
              mode: 802.3ad
              slaves:
                - interface-name:
                     value: enp59s0f0
                - interface-name:
                     value: enp59s0f1
          - name: enp59s0f0
            type: ethernet
            state: up
            mtu: 1500
	    ethtool:
		ring:
	          rx: 2048
		  rx-mini: 0
		  rx-jumbo: 0
		  tx: 2048
          - name: enp59s0f1
            type: ethernet
            state: up
            mtu: 1500
	    ethtool:
		ring:
	          rx: 2048
		  rx-mini: 0
		  rx-jumbo: 0
		  tx: 2048
```

Without ethtool settings our deployment works perfectly.
