### ISSUE TITLE
Bug report: Configuration examples use the wrong ports directive

### ISSUE THREAD

**Issue by tale-toul** [nmstate/nmstate#1941]
## Describe the bug
The bond and team examples in the documentation at https://nmstate.io/examples.html use the directive __ports:__ instead of the singular form __port:__

When validating the configuration with nmstatectl the resulting output is not valid

## Nmstate version
nmstatectl --version
1.2.1

## Platform
RHEL 8.6

## Steps to Reproduce
Copying the example from the page and passing it to nmstatectl yields 
Example:
```
interfaces:
- name: bond99
  type: bond
  state: up
  ipv4:
    address:
    - ip: 192.0.2.0
      prefix-length: 24
    enabled: true
  link-aggregation:
    mode: balance-rr
    options:
      miimon: '140'
    ports:
    - eth3
    - eth2
```

Output from nmstatectl gc, contains no configuration for the eth NICs
```
---
NetworkManager:
- - bond99.nmconnection
  - '[connection]

    id=bond99

    uuid=e1352cf2-5ada-490a-ac38-82e9d9f29690

    type=bond

    autoconnect-slaves=1

    interface-name=bond99


    [bond]

    miimon=140

    mode=balance-rr


    [ipv4]

    address1=192.0.2.0/24

    dhcp-client-id=mac

    method=manual


    [ipv6]

    addr-gen-mode=eui64

    dhcp-duid=ll

    dhcp-iaid=mac
   method=disabled


    [proxy]

    '
```

When using the singular form __port:__ 
```
interfaces:
- name: bond99
  type: bond
  state: up
  ipv4:
    address:
    - ip: 192.0.2.0
      prefix-length: 24
    enabled: true
  link-aggregation:
    mode: balance-rr
    options:
      miimon: '140'
    port:
    - eth3
    - eth2
```
The output from nmstatectl contains the configuration section for the eth NICs:
```
---
NetworkManager:
- - bond99.nmconnection
  - '[connection]

    id=bond99

    uuid=4077a29d-0cc8-452d-afb5-ab158df9069c

    type=bond

    autoconnect-slaves=1

    interface-name=bond99


    [bond]

    miimon=140

    mode=balance-rr


    [ipv4]

    address1=192.0.2.0/24

    dhcp-client-id=mac

    method=manual


    [ipv6]

    addr-gen-mode=eui64

    dhcp-duid=ll

    dhcp-iaid=mac
    method=disabled


    [proxy]

    '
- - eth3.nmconnection
  - '[connection]

    id=eth3

    uuid=416b6f2b-7110-410c-8696-958beeb1fd6f

    type=ethernet

    interface-name=eth3

    master=bond99

    slave-type=bond


    [ethernet]

    '
- - eth2.nmconnection
  - '[connection]

    id=eth2

    uuid=92147ac5-58ab-46df-b6e4-79530b71494c

    type=ethernet

    interface-name=eth2

    master=bond99

    slave-type=bond


    [ethernet]

    '
```
