### ISSUE TITLE
Nmstate set command is failing for the route rules 

### ISSUE THREAD

**Issue by emxxved** [nmstate/nmstate#1974]
## Nmstate version
- Version 1.2.0

## NetworkManager version
- Version 1.36.6

## Platform
CentOS 6

## How reproducible
apply the configurations

## Steps to Reproduce

Failure 1:
When try to nmstatectl set the below  route rules, with not giving any priority then its rejected by the nmstatectl. This is failing when nsmtatectl has currently one route rule with default priority set. Failure_1.txt contains the logs for this error. 

 

`-route-rules:
  config:
  - ip-from: 5.4.3.0/24
    ip-to: 192.168.0.0/24
    priority: 29995
    route-table: 254
  - ip-from: 6.5.3.0/24
    route-table: 254
  - ip-from: 7.5.3.0/24
    route-table: 254`
 
[Failure_1.txt](https://github.com/nmstate/nmstate/files/9131714/Failure_1.txt)

Failure 2:

When nmstatectl set route rules for two different route-table Ids, nmstatectl rejects the config. Failure_2.txt contains logs for this error. when we try to apply the config for the table 254 it works. but does not work for table 200.

`route-rules:
  config:
  - ip-from: 5.4.3.0/24
    ip-to: 192.168.0.0/24
    priority: 29995
    route-table: 254
  - ip-from: 6.4.3.0/24
    ip-to: 201.168.0.0/24
    priority: 29995
    route-table: 200`
 
[Failure_2.txt](https://github.com/nmstate/nmstate/files/9131709/Failure_2.txt)

**Comment by nmathew** [comment]
@cathay4t @ffmancera Any pointers?

In the first case:

We configured:

```
-route-rules:
config:
-  ip-from: 5.4.3.0/24
   ip-to: 192.168.0.0/24
   priority: 29995
   route-table: 254
-  ip-from: 6.5.3.0/24
   route-table: 254
-  ip-from: 7.5.3.0/24
   route-table: 254

```

output:

```
desired

---
route-rules:
  config:
  - ip-from: 5.4.3.0/24
    ip-to: 192.168.0.0/24
    priority: 29995
    route-table: 254
  - ip-from: 6.5.3.0/24
    ip-to: ''
    route-table: 254
  - ip-from: 6.5.3.0/24
    ip-to: ''
    priority: 30000
    route-table: 254
  - ip-from: 7.5.3.0/24
    ip-to: ''
    route-table: 254

current

---
route-rules:
  config:
  - ip-from: 5.4.3.0/24
    ip-to: 192.168.0.0/24
    priority: 29995
    route-table: 254
  - ip-from: 6.5.3.0/24
    ip-to: ''
    priority: 30000
    route-table: 254
  - ip-from: 7.5.3.0/24
    ip-to: ''
    priority: 30000
    route-table: 254

difference

--- desired
+++ current
@@ -7,11 +7,9 @@
     route-table: 254
   - ip-from: 6.5.3.0/24
     ip-to: ''
-    route-table: 254
-  - ip-from: 6.5.3.0/24
-    ip-to: ''
     priority: 30000
     route-table: 254
   - ip-from: 7.5.3.0/24
     ip-to: ''
+    priority: 30000
     route-table: 254
```
Why desired is showing two "ip-from: 6.5.3.0/24" since default priority is 30000?
