### ISSUE TITLE
nmstatectl does not fail anymore when using an invalid ip address

### ISSUE THREAD

**Issue by andfasano** [nmstate/nmstate#2311]
## Describe the bug
In a previous version (1.3.4) the `nmstatectl gc` command failed when an invalid configuration was provided, specifically an IPv4 address in a IPv6 stanza. Using the version 2.2.9 instead the invalid configuration is accepted

## Nmstate version
- 2.2.9

## NetworkManager version
- 1.40.0

## Platform
- RHEL 8.7

## How reproducible
- 100%

## Steps to Reproduce
Create the following config file `test.yaml` (an IPv4 address is wrongly specified in the IPv6 stanza): 
```
interfaces:
- ipv6:
    address:
    - ip: 192.168.122.21
      prefix-length: 24
    enabled: true
  mac-address: 52:54:01:aa:aa:a1
  name: eth0
  state: up
  type: ethernet
```

Run `nmstatectl gc test.yaml`

## Nmstate output
- Expected output:
```
...
GLib.Error: nm-connection-error-quark: Invalid IPv6 address '192.168.122.21' (0)
```
with a non-zero rc

- Current output:
```
NetworkManager:
- - eth0.nmconnection
  - |
    [connection]
    autoconnect=true
    autoconnect-slaves=-1
    id=eth0
    interface-name=eth0
    type=802-3-ethernet
    uuid=dfd202f5-562f-5f07-8f2a-a7717756fb70

    [ipv4]
    method=disabled

    [ipv6]
    addr-gen-mode=0
    method=link-local

    [ethernet]
    cloned-mac-address=52:54:01:AA:AA:A1
```
with a zero rc

### Additional context
-
