### ISSUE TITLE
[RFE] Allowing referring bond/bridge/vlan/etc port using profile name

### ISSUE THREAD

**Issue by ryanbowen** [nmstate/nmstate#2380]
Right now the interface name is required to configure an interface. It would be nice to be able to apply config to ethernet interfaces by using either the permanent MAC address **_or_** the name. 

NetworkManager allows you to create connection profiles that are mapped to interfaces by MAC address without requiring the interface name. This is nice because it saves you when certain NIC manufacturers (_looking at you, Mellanox..._) decide to make changes to drivers or firmware that alter the "predictable" interface names which would otherwise cause host networking to break on boot. Obviously this can be solved with udev rules but it would be nice to not have to resort to them.

**Comment by cgwalters** [comment]
This is strongly related to https://github.com/nmstate/nmstate/pull/2301 - note we solved that by writing systemd .link files.
>  Obviously this can be solved with udev rules but it would be nice to not have to resort to them.

Yes, but note systemd .link files are already declarative and much nicer than udev rules.

**Comment by cathay4t** [comment]
Tihs is already supported since 2.2.10. For example:

```yml
---
interfaces:
  - name: wan0
    type: ethernet
    state: up
    identifier: mac-address
    mac-address: 1e:bd:23:e9:fb:94
    ipv4:
      enabled: true
      dhcp: true
    ipv6:
      enabled: true
      dhcp: true
      autoconf: true
```

**Comment by cathay4t** [comment]
I have created document at https://nmstate.io/features/mac_identifier.html

**Comment by cathay4t** [comment]
@cgwalters ^^

**Comment by ryanbowen** [comment]
Thanks, great to hear that this is supported now. Can this be used as a way to use MAC addresses to specify bond member ports? Does nmstate match the names used in `interface.link-aggregation.port(s)` to nmstate `interface.name` or directly to kernel device names? 

i.e. does this work if the kernel device names aren't `bond0-member0` and `bond0-member1`:
``` yaml
interfaces:
- name: bond0
  type: bond
  state: up
  link-aggregation:
    mode: 802.3ad
    options:
      ...
    port:
    - bond0-member0
    - bond0-member1
- name: bond0-member0
  type: ethernet
  state: up
  identifier: mac-address
  mac-address: 1E:BD:23:E9:FB:94
  ...
- name: bond0-member1
  type: ethernet
  state: up
  identifier: mac-address
  mac-address: 1E:BD:23:E9:FB:95
  ...
``` 

Alternatively, is there a way to specify the parent/controller/master of an interface on the child?
``` yaml
- name: bond0-member0
  type: ethernet
  state: up
  identifier: mac-address
  mac-address: 1E:BD:23:E9:FB:94
  controller: bond0
```

For context, we run LACP for the majority of our hosts and the interface renaming hurts the most with bonds because the we end up with no functional members. With non-bonded interfaces, it seems NetworkManager will fall back to a default profile with DHCP on one of the interfaces when no other connection profiles match, so at least we don't lose networking completely. With LACP bonds, when things get renamed we end up without any functional networking at all and have to fix it by getting on the console via the BMC which doesn't scale. I just still haven't found the magic solution that works with LACP bonds AND can be applied via nmstate.

**Comment by bowenr-deshaw** [comment]
@cathay4t @cgwalters Do either of you know if one of the strategies above allow specifying bond member ports in a way that matches based on MAC and not kernel device name?

**Comment by cathay4t** [comment]
@ryanbowen Currently nmstate does not support referring the profile name of a interface as port yet. But workaround could be:
 1. Create bond with empty port list.
 2. Add port to this bond.
 
For example, apply these two YAML __seperately__ will work for your use case:

```yml
---
interfaces:
- name: bond0
  type: bond
  state: up
  link-aggregation:
    mode: balance-rr
    ports: []
```

```yml
---
interfaces:
- name: bond0-member0
  type: ethernet
  state: up
  identifier: mac-address
  mac-address: c2:9f:53:47:5d:08
  controller: bond0
```

I have create https://issues.redhat.com/browse/RHEL-1745 to trace the effort on supporting this in single YAML file.

**Comment by ryanbowen** [comment]
@cathay4t I'm unable to view that Red Hat Jira issue you mentioned ([RHEL-1745](https://issues.redhat.com/browse/RHEL-1745)), unless that's expected. We also have a RH support contract w/TAM services in case it's needed or helps.

**Comment by cathay4t** [comment]
@ryanbowen Please contact your TAM or support engineer for access. We are currently planning it for OCP 4.14 or later version, if you need backport to older version of openshift, please mention that to your TAM/support contact. Thank you!

**Comment by drawks** [comment]
This feature would be great, however all of the last several messages in this issue direct to resources off site and or refer to various commercial support contracts and/or tangental software. Can this issue please get an update that clearly communicates whether this feature is being worked on and if so what the expected release timeline is?

All the top level documentation for this project suggests that PRs are welcome, but pivoting issues to pay walled tickets and support contracts makes it hard to tell if progress is being made and/or coordinate additional contributions to the requested feature.

**Comment by cathay4t** [comment]
@drawks You may ignore those redhat links, they just tracks the effort of backport this feature into Red Hat linux. For upstream, I am currently working on this feature and expected to include it in next release 2.2.28 before 2024 Apr 26.

**Comment by hjensas** [comment]
Also for vlan interfaces it would be nice to be able to define the "base-iface" using a name.

Something like:
```
- name: net-iso
  type: ethernet
  identifier: mac-address
  mac-address: 52:54:00:5b:39:8b
- name: net-iso.101
  type: vlan
  state: up
  vlan:
    base-iface: net-iso
    id: 101
    protocol: 802.1q
```

**Comment by cathay4t** [comment]
I am still coding on this. This is way complex(very hard to pass overbook validation).

If you cannot wait, please use this YAML which is already support in nmstate:

```yml
capture:
  port1: interfaces.mac-address=="00:23:45:67:89:1B"
  port2: interfaces.mac-address=="00:23:45:67:89:1A"
desiredState:
  interfaces:
  - name: bond0
    type: bond
    state: up
    link-aggregation:
      mode: active-backup
      ports:
        - "{{ capture.port1.interfaces.0.name }}"
        - "{{ capture.port2.interfaces.0.name }}"
```

It is nmpolicy nmstate support natively. You can do similar stuff for VLAN base-iface also.

Note: Please use upper case for MAC address, it is a tiny bug to nmstate nmpolicy. :)

**Comment by cathay4t** [comment]
VRF, bond, linux bridge support is done at https://github.com/nmstate/nmstate/pull/2710

OVS bridge code is in that PR also, but NetworkManager has bug for it: https://issues.redhat.com/browse/RHEL-34617 , once fixed, nmstate should support it without additional changes.

Example YAML for bond:

```yml
interfaces:
- name: bond0
  type: bond
  state: up
  link-aggregation:
    mode: balance-rr
    ports-config:
    - profile-name: bond0-port1
    - profile-name: bond0-port2
- name: bond0-port1
  type: ethernet
  state: up
  identifier: mac-address
  mac-address: 00:23:45:67:89:1a
- name: bond0-port2
  type: ethernet
  state: up
  identifier: mac-address
  mac-address: 00:23:45:67:89:1b
```

Example YAML for Linux bridge:

```yaml
interfaces:
- name: br0
  type: linux-bridge
  state: up
  bridge:
    port:
    - profile-name: br0-port1
- name: br0-port1
  type: ethernet
  state: up
  identifier: mac-address
  mac-address: 00:23:45:67:89:1a
```

Example VRF YAML:

```yml
interfaces:
- name: vrf0
  type: vrf
  state: up
  vrf:
    port: null
    route-table-id: 100
    ports-config:
    - profile-name: vrf0-port1
    - profile-name: vrf0-port2
- name: vrf0-port1
  type: ethernet
  state: up
  identifier: mac-address
  mac-address: 00:23:45:67:89:1a
- name: vrf0-port2
  type: ethernet
  state: up
  identifier: mac-address
  mac-address: 00:23:45:67:89:1b
```

Will do another PR for parent referring (VLAN/VxLAN/MacVLAN/etc).

**Comment by cathay4t** [comment]
For anyone needing this feature, could you explains why your use case cannot use `nmpolicy` mentioned above?

Nmstate team is having concern of introducing this property is violation of `declarative` design.

**Comment by bowenr-deshaw** [comment]
Thanks for the update! This is great news.

> For anyone needing this feature, could you explains why your use case cannot use nmpolicy mentioned above?
> 
> Nmstate team is having concern of introducing this property is violation of declarative design.

Honestly what it comes down to is:
1. I want to rely on DHCP as little as possible. Most examples in nmpolicy depend on determining interfaces based on routes picked up from DHCP to map policies to physical interfaces. We purposely do not provide DHCP to any interface outside of the one used for the initial PXE and even then it's the bare minimum.
2. `nmpolicy` is essentially jinja templates with less control. I have a very heterogeneous environment and I'd prefer to render my own explicit nmstate configs based on what's defined in our "single source of truth" system vs using heuristics. It's nice being able to say to our provisioning system "give me my exact network config based on who you think I am" then applying it in a single transaction, which is what this RFE allows. 
3. IMO declarative design went out the window when Mellanox and Solarflare (well Xilinx really) were able to make changes to firmware/kernel modules that altered kernel interface names and broke networking on boot in a way that required manual intervention. I'd argue that relying on kernel device naming for _anything_ is a violation of declarative design. Permanent MAC address may be the only thing left I can actually use to somewhat reliably identify a physical interface at build time, and even then it's a stretch.

**Comment by zaneb** [comment]
The following input to nmstatectl 2.2.21:
```
interfaces: 
- name: bond0
  type: bond
  state: up
  link-aggregation: 
    mode: balance-rr
    ports: 
    - bond0-port1
    - bond0-port2
- name: bond0-port1
  type: ethernet
  state: up
  identifier: mac-address
  mac-address: 00:23:45:67:89:1a
- name: bond0-port2
  type: ethernet
  state: up
  identifier: mac-address
  mac-address: 00:23:45:67:89:1b
```

generates the following output from `nmstatectl gc`:

```
- - bond0.nmconnection
  - |
    [connection]
    autoconnect=true
    autoconnect-slaves=1
    id=bond0
    interface-name=bond0
    type=bond
    uuid=925b4a95-2de0-5b2d-bcf5-8b684a7e9cb4

    [bond]
    mode=balance-rr

    [ipv4]
    dhcp-timeout=2147483647
    method=disabled

    [ipv6]
    dhcp-timeout=2147483647
    method=disabled
- - bond0-port1.nmconnection
  - |
    [connection]
    autoconnect=true
    autoconnect-slaves=-1
    id=bond0-port1
    master=925b4a95-2de0-5b2d-bcf5-8b684a7e9cb4
    slave-type=bond
    type=802-3-ethernet
    uuid=2780436c-eca3-5012-b351-9abed7c1ecd7

    [ethernet]
    mac-address=00:23:45:67:89:1A
- - bond0-port2.nmconnection
  - |
    [connection]
    autoconnect=true
    autoconnect-slaves=-1
    id=bond0-port2
    master=925b4a95-2de0-5b2d-bcf5-8b684a7e9cb4
    slave-type=bond
    type=802-3-ethernet
    uuid=3391a485-8739-5707-93bc-f8b177eabf55

    [ethernet]
    mac-address=00:23:45:67:89:1B
```

That looks pretty plausible to me (port keyfiles look similar to how they do without the bond; bond keyfile does not contain references to the dummy port names).  Is the issue that this doesn't work with `nmstatectl apply`? Or that the ports always need to be applied as part of the same nmstate file as the bond (i.e. you can't just apply the bond by itself and expect it to pick up the profile names)?

The [VLAN thing mentioned by Harald](https://github.com/nmstate/nmstate/issues/2380#issuecomment-2094149114) doesn't look like it will work though, because the VLAN interface refers to the port names (whereas in the bond case it's the ports that refer to the bond). Applying the VLAN on top of a bond with 1 member seems like it would probably work.

**Comment by cathay4t** [comment]
> That looks pretty plausible to me (port keyfiles look similar to how they do without the bond; bond keyfile does not contain references to the dummy port names). 

That's correct YAML and keyfile.

> Is the issue that this doesn't work with nmstatectl apply? 

It works both for `gc` and `apply`.

> Or that the ports always need to be applied as part of the same nmstate file as the bond (i.e. you can't just apply the bond by itself and expect it to pick up the profile names)?

Both separate YAMLs and all-in-one YAML should works.

**Comment by cathay4t** [comment]
I have tested these YAMLs on nmstate 2.2.21 for bond/bridge/vrf MAC address referring by using `controller` property. For example:

```yml
---
interfaces:
  - name: bond0
    type: bond
    link-aggregation:
      mode: balance-rr
  - name: bond0-port1
    type: ethernet
    state: up
    identifier: mac-address
    mac-address: 00:23:45:67:89:1a
    controller: bond0
```

So the remaining problems are:
 * OVS bridge
 * VLAN/VxLAN and other parent-child relationship.
 * Bridge VLAN filtering is impossible for `controller` property method.

I will continue my work on https://github.com/nmstate/nmstate/pull/2710 to provide proper support on this use case.
