### ISSUE TITLE
No support for Vxlan local option 

### ISSUE THREAD

**Issue by k8scoder192** [nmstate/nmstate#2394]
## In Netplan, you can specify a vxlan config with "local" as an option

```
    network:
      version: 2
      renderer: NetworkManager
      ethernets:
        lo:
          addresses:
            - <LOOPBACK_IP>/32
      bridges:
        VLAN500:
          interfaces: [vxlan500]
      tunnels:
        vxlan500:
          mode: vxlan
          link: lo
          id: 500
          accept-ra: no
          neigh-suppress: true
          mac-learning: false
          port: 4789
          local: <LOOPBACK_IP>
````

or via ifupdown version 
```
auto vxlan500
iface vxlan500 inet manual
    pre-up ip link add vxlan500 type vxlan id 500 dstport 4789 local <LOOP_IP> dev lo || true
    up ip link set vxlan500 up
    down ip link set vxlan500 down
    post-down ip link del vxlan500 || true

auto VLAN500
iface VLAN500 inet manual
    bridge-ports vxlan500
```
However, per the spec [VXLAN](https://nmstate.io/devel/api.html#vxlan) there is no option for local. It appears that nmstate only allows/does is set up a point to point unicast VXLAN tunnel with a known end point. However, with our configuration we use EVP to to figure the dest IPs dynamically

Is this functionality something that can be added?

**### EDIT**
It looks like nmstatectl 2.2.13 does support "local" but it is NOT documented 
Can someone please update the [API doc](https://nmstate.io/devel/api.html) and [examples doc](https://nmstate.io/examples.html)?

Here is an example yaml
```
---
interfaces:
  - name: vxlan103
    type: vxlan
    state: up
    vxlan:
      base-iface: ens11
      id: 103
      destination-port: 4789
      local: 11.0.15.3
```

## Nmstate version
- Version [e.g. 0.3.1]

## NetworkManager version
- Version [e.g. 1.24.2]

## Platform
- Platform: [e.g. CentOS 6]

## How reproducible
- [e.g. 100%, random]

## Steps to Reproduce
Steps to reproduce the issue as yaml. [e.g. `cat example.yaml`]

## Nmstate output
- Expected output:

- Current output:
