### ISSUE TITLE
Feature Request: Support config interface ifalias

### ISSUE THREAD

**Issue by halfcrazy** [nmstate/nmstate#2517]
xref https://github.com/containernetworking/plugins/issues/992

**Comment by cathay4t** [comment]
Hi @halfcrazy , this feature need NetworkManager support first.

Meanwhile, could you provide more information on how you will use it?

**Comment by cathay4t** [comment]
@halfcrazy ping

**Comment by halfcrazy** [comment]
> @halfcrazy ping

Sorry for the delay. My use case is aliases to mark nics with different names with the same role on different nodes. Then I can use aliases, eg role: management to manage those nics.

**Comment by cathay4t** [comment]
Something like `ip link property add dev eth1 altname wan0` ?

```yml
---
interfaces:
  - name: main    # not kernel interface name
    type: ethernet
    identifer: mac-address # search this interface by MAC
    state: up
    mac-address: 00:23:45:67:89:1b
    alt-names:
      - primary
      - long-name-than-15-bits
    ipv4:
      address:
      - ip: 192.0.2.251
        prefix-length: 24
      dhcp: false
      enabled: true
routes:
  config:
  - destination: 0.0.0.0/0
    next-hop-address: 192.0.2.1
    next-hop-interface: long-name-than-15-bits
  - destination: 198.51.100.0/24
    next-hop-address: 192.0.2.1
    next-hop-interface: wan0
```
