### ISSUE TITLE
Feature request: per-interface DNS resolver settings

### ISSUE THREAD

**Issue by mjsaarin** [nmstate/nmstate#2538]
I am able to set per-interface DNS resolver settings with nmcli. The same cannot be achieved with nmstatectl. Am I doing something wrong or is this feature missing?

```
# nmcli c show enp1s0 | grep ipv4.dns:
ipv4.dns:                               8.8.8.8,1.1.1.1
# nmstatectl show enp1s0 
dns-resolver: {}
route-rules: {}
# nmstatectl show 
hostname:
  running: ...
  config: ...
dns-resolver:
  running:
    server:
    - 8.8.8.8
    - 1.1.1.1
```

I would expect the nmstatectl output to show the same information that was set with nmcli.
