### ISSUE TITLE
Please think long and hard about using FreeS/WAN's {left,right} in the config files.

### ISSUE THREAD

**Issue by cagney** [nmstate/nmstate#2568]
Libreswan's left/right syntax can be seen in nmstate's [IPsec](https://nmstate.io/features/ipsec.html) examples vis (i tweaked it as it had left=right):

```
interfaces:
- name: hosta_conn
  type: ipsec
  ipv4:
    enabled: true
    dhcp: true
  libreswan:
    ipsec-interface: "99"
    left: 192.0.2.250
    leftid: '%fromcert'
    leftcert: hosta.example.org
    right: 192.0.2.150
    rightid: '%fromcert'
    ikev2: insist
    ikelifetime: 24h
    salifetime: 24h
```

This syntax can be traced back to the '90's and FreeS/WAN.  While it seemed to be a good idea at the time, it hasn't aged well.   I'm not sure that nmstate preserving it is a good idea.

Let me try to explain with an example:

- when writing a swan configuration file, the first step to draw a diagram
(there's a convention that the server is put on the right and the client is on the left; but beyond that things are arbitrary)
```
192.0.2.150  === 192.0.2.250 hosta.example.org 
```
- this diagram is then converted into a config file where everything on the LHS is labeled left, and RHS is labeled right; the next convention is use the same or similar config files so that left/right mean the same thing on both ends:
```
conn to-hosta
    left=192.0.2.150
    right=192.0.2.250
    rightid=hosta.example.org
    ...
```
- the above would then be pasted into the server and client (here's my attempt at the client):
```
interfaces:
- name: hostb_conn
  type: ipsec
  ipv4:
    enabled: true
    dhcp: true
  libreswan:
    ipsec-interface: "99"
    left: 192.0.2.150
    leftid: '%fromcert'
    rightcert: hosta.example.org
    right: 192.0.2.250
    rightid: '%fromcert'
    ikev2: insist
    ikelifetime: 24h
    salifetime: 24h
```
Looking at the nmstate, the examples are more in line with client/server and/or local/remote in their approach.   For instance:
```
  ipv4:
    address:
    - ip: 192.0.2.142
      prefix-length: 24
    enabled: true
```
is describing the local end, and not an arbitrarily assigned left/right end.   Having one config contain`ip: 192.0.2.142` and the other contain `left: 192.0.2.142` (or is that right:) to me is confusing.

If I look through libreswan's bug database and posts, no one seems to do this and instead try to adopt left=local say.

Can I encourage nmstate to think carefully about how to approach this.  Even local-id: remote-id: which then gets translated before being fed to libreswan.
