### ISSUE TITLE
Demo for using  natural language to generate nmstate YAML for linux bridge.

### ISSUE THREAD

**Issue by cathay4t** [nmstate/nmstate#2583]
Input: `Please create a linux bridge br0 using eth1 and eth2`.

Output:

```yml
---
interfaces:
  - name: br0
    type: linux-bridge
    state: up
    bridge:
      ports:
        - name: eth1
        - name: eth2
```

Please treat it as natural language parsing, not regex string parsing on input.
