### ISSUE TITLE
Different output running inside Docker 

### ISSUE THREAD

**Issue by egimbernat** [nmstate/nmstate#2644]
## Describe the bug
I've been trying to run a simple query inside a Docker container where DBUS is mounted and environment variables are set to allow NetworkManager to connect.
Running nmcli returns the expected details, but doing the same using nmstate gives different results. Both binaries are run inside the container

## Nmstate version
- Version 2.2.27

## NetworkManager version
- Version 1.30

## Platform
- Platform: Debian

## How reproducible
- Always on different devices and different architectures

## Steps to Reproduce
Simple `nmstate show` and `nmcli` outputs

## Nmstate output
- Expected output:
NMCLI output
```
enp0s3: connected to Wired connection 1
        "enp0s3"
        ethernet (virtio_net), 52:54:00:12:34:56, hw, mtu 1500
        ip4 default, ip6 default
        inet4 10.0.2.15/24
        route4 0.0.0.0/0
        route4 10.0.2.0/24
        inet6 fec0::50c0:5526:9bc9:b089/64
        inet6 fe80::45de:6d24:d53:ad3d/64
        route6 fec0::/64
        route6 ::/0
        route6 fe80::/64

supervisor0: connected (externally) to supervisor0
        "supervisor0"
        bridge, 02:42:8C:B3:A2:45, sw, mtu 1500
        inet4 10.114.104.1/25
        route4 10.114.104.0/25
        inet6 fe80::42:8cff:feb3:a245/64
        route6 fe80::/64

br-6829e80f8c88: unmanaged
        "br-6829e80f8c88"
        bridge, 02:42:C8:E4:9C:13, sw, mtu 1500

resin-dns: unmanaged
        "resin-dns"
        bridge, D6:F4:31:35:42:B1, sw, mtu 1500

veth9f7b4e6: unmanaged
        "veth9f7b4e6"
        ethernet (veth), 32:98:6D:D4:04:A4, sw, mtu 1500

vethba3e99b: unmanaged
        "vethba3e99b"
        ethernet (veth), AE:4C:E6:23:D3:69, sw, mtu 1500

vethca54b97: unmanaged
        "vethca54b97"
        ethernet (veth), 86:1B:65:53:F3:51, sw, mtu 1500

sit0: unmanaged
        "sit0"
        iptunnel (sit), 00:00:00:00, sw, mtu 1480

lo: unmanaged
        "lo"
        loopback (unknown), 00:00:00:00:00:00, sw, mtu 65536

resin-vpn: unmanaged
        "resin-vpn"
        tun, sw, mtu 1500

DNS configuration:
        servers: 10.0.2.3
        interface: enp0s3
```
        
- Current output:
```
hostname:
  running: f1b0f05df68f
  config: f1b0f05df68f
dns-resolver:
  running:
    server:
    - 10.0.2.3
    search: []
  config: {}
route-rules:
  config: []
routes:
  running:
  - destination: 0.0.0.0/0
    next-hop-interface: eth0
    next-hop-address: 172.17.0.1
    table-id: 254
  config:
  - destination: 0.0.0.0/0
    next-hop-interface: eth0
    next-hop-address: 172.17.0.1
    table-id: 254
interfaces:
- name: br-6829e80f8c88
  type: linux-bridge
  state: ignore
- name: enp0s3
  profile-name: Wired connection 1
  type: ethernet
  state: up
  identifier: name
  wait-ip: any
  ipv4:
    enabled: true
    dhcp: true
    auto-dns: true
    auto-gateway: true
    auto-routes: true
    auto-route-table-id: 0
    dhcp-send-hostname: true
  ipv6:
    enabled: true
    dhcp: true
    autoconf: true
    auto-dns: true
    auto-gateway: true
    auto-routes: true
    auto-route-table-id: 0
    addr-gen-mode: stable-privacy
    dhcp-send-hostname: true
  lldp:
    enabled: false
- name: eth0
  type: veth
  state: up
  mac-address: 02:42:AC:11:00:02
  mtu: 1500
  min-mtu: 68
  max-mtu: 65535
  ipv4:
    enabled: true
    address:
    - ip: 172.17.0.2
      prefix-length: 16
  ipv6:
    enabled: false
  mptcp:
    address-flags: []
  accept-all-mac-addresses: false
- name: eth1
  type: veth
  state: up
  mac-address: 02:42:0A:72:68:02
  mtu: 1500
  min-mtu: 68
  max-mtu: 65535
  ipv4:
    enabled: true
    address:
    - ip: 10.114.104.2
      prefix-length: 25
  ipv6:
    enabled: false
  mptcp:
    address-flags: []
  accept-all-mac-addresses: false
- name: lo
  type: loopback
  state: ignore
  mac-address: 00:00:00:00:00:00
  mtu: 65536
  ipv4:
    enabled: true
    address:
    - ip: 127.0.0.1
      prefix-length: 8
  ipv6:
    enabled: false
  accept-all-mac-addresses: false
- name: resin-dns
  type: linux-bridge
  state: ignore
- name: sit0
  type: unknown
  state: ignore
- name: supervisor0
  type: linux-bridge
  state: up
- name: veth9f7b4e6
  type: ethernet
  state: ignore
- name: vethba3e99b
  type: ethernet
  state: ignore
- name: vethca54b97
  type: ethernet
  state: ignore
```

I'm running out of ideas. Any suggestion?
