### ISSUE TITLE
[Schema] Request for comment on WIFI schema

### ISSUE THREAD

**Issue by cathay4t** [nmstate/nmstate#2720]
Use case:
1. Apply WIFI PSK credential to any wifi interface when specified ESSID found.
2. Apply WIFI PSK credential dedicate to specified WIFI interface.
3. Able to set different IP, MTU, ethtool and etc settings for different ESSID even they will be running on the same physical interface.

Example YAML:

```yml
interfaces:
  - name: home_wifi
    # ^ The name is not kernel interface name, but a profile name for this wifi
    # connection. We cannot place wifi settings to WIFI NIC, because eash ESSID
    # might have different IP settings.
    type: wifi
    # up: activate and verify wifi connectioned
    # down: means store it to config, deactivate, only verify whether config
    #       applied
    # absent: deactivate and remove config
    state: up
    wifi:
      essid: CrackMe
      psk: <hid_by_nmstate>
      # base-iface is OK to be not defined when applying.
      base-iface: wlan0
      # whether ESSID config is for specified interface only.
      # the reason we did not use `base-iface` for this: when querying, we would like to include
      # base interface for this wifi connection even it is not bind to this interface for querying.
      bind-to-iface: false
      # we could also provide more query only status like WIFI generation, speed, signal strength and etc.
    ipv4:
      enabled: true
      dhcp: true
    ipv6:
      enabled: false
```
