### ISSUE TITLE
[Schema] Refer controller port by MAC address

### ISSUE THREAD

**Issue by cathay4t** [nmstate/nmstate#2729]
# Use case

Create a bond with ports holding specified MAC address regardless the interface
name changed or not after reboots

# Proposed schema

Introduce `match` section to `ports` or `ports-config` section of
bond/bridge/VRF. The `match` section is:

```yml
match:
  name: eth1
  mac-address: 00:23:45:67:89:1a
  iface-type: ethernet
```

If not match section, port is matched by using interface name. Once `match`
section included, __ALL__ properties in that section will be use for searching
the interface.

The match section is full editing, if mentioned, it will just override
current setting without any merging.

For querying on name matching port, the `match` section will be set as:

```yml
match:
  name: eth1
```

## Example: Attach `00:23:45:67:89:1a` and `00:23:45:67:89:1b` to bond

Desired state:

```yml
---
interfaces:
- name: bond0
  type: bond
  state: up
  link-aggregation:
    mode: balance-rr
    ports-config:
    - match:
        mac-address: 00:23:45:67:89:1a
        iface-type: ethernet
    - match:
        mac-address: 00:23:45:67:89:1b
        iface-type: ethernet
```

Post-apply query state:

```yml
---
interfaces:
- name: bond0
  type: bond
  state: up
  link-aggregation:
    mode: balance-rr
    port:
    - eth1
    - eth2
    ports-config:
    - name: eth1
      match:
        mac-address: 00:23:45:67:89:1a
        iface-type: ethernet
    - name: eth2
      match:
        mac-address: 00:23:45:67:89:1b
        iface-type: ethernet
```

## Example: Attach `00:23:45:67:89:1a` and `00:23:45:67:89:1b` to linux bridge

Desired state:

```yml
---
interfaces:
  - name: br0
    type: linux-bridge
    state: up
    bridge:
      port:
        - match:
            mac-address: 00:23:45:67:89:1a
            iface-type: ethernet
        - match:
            mac-address: 00:23:45:67:89:1b
            iface-type: ethernet
```

Post-apply state:

```
---
interfaces:
  - name: br0
    type: linux-bridge
    state: up
    bridge:
      port:
        - name: eth1
          match:
            mac-address: 00:23:45:67:89:1a
            iface-type: ethernet
        - name: eth2
          match:
            mac-address: 00:23:45:67:89:1b
            iface-type: ethernet
```

For OVS, just replace `linux-bridge` with `ovs-bridge`

## Exampel: Attach `00:23:45:67:89:1a` and `00:23:45:67:89:1b` to VRF

Desired state:

```yml
---
interfaces:
- name: vrf100
  type: vrf
  state: up
  vrf:
    route-table-id: "100"
    ports-config:
    - match:
        mac-address: 00:23:45:67:89:1a
        iface-type: ethernet
    - match:
        mac-address: 00:23:45:67:89:1b
        iface-type: ethernet
```

Post apply query state:

```yml
---
interfaces:
- name: vrf100
  type: vrf
  state: up
  vrf:
    route-table-id: "100"
    port:
    - eth1
    - eth2
    ports-config:
    - name: eth1
      match:
        mac-address: 00:23:45:67:89:1a
        iface-type: ethernet
    - name: eth2
      match:
        mac-address: 00:23:45:67:89:1b
        iface-type: ethernet
```

# Better

 * Easier to expand to more match methods.

# Worse
 * More validation required. (but acceptable)

# Other schema considered

## A: Refer by profile name

```yml
ports:
  - profile-name: bond0-port1
```

With this, we can reuse the `match: mac-address` in the `interfaces` section.
And also easy to expand this `match` without changes to bond/bridge/vrf
section.  But this schema requires extra document to explain how to achieve the
original use case by setting the port interface as `match: mac-address` with
profile name first.

## B: No `match` in port section

Without `match`, we cannot tell whether current status is mac based or
interface name based because query state will include both MAC address and
interface name.

## C: Use `NetworkPolicy` (aka nmpolicy)

By using `NetworkPolicy`, nmstate can find out the interface name on MAC
address, but this will hard code interface name into desire state, so follow up
changes to NIC name will not works.

**Comment by ihuguet** [comment]
If I understood well, we need the `identifier:` field mainly because if you get a state by querying, and want to apply it, both the interface name and MAC appear, and we need to know how to match.

But we could make it optional: if the desired state doesn't contain `name` and contains `mac-address`, we add `identifier: mac-address` implicitly. Later, if the state is queried, it is not a problem to print `identifier: mac-address`: it is what we are using and it was implied in the desired state that it's what the user wanted.

Doing that, the case "query & apply" will still work, and we will save the users from having to type `identifier: mac-address` every time if they are hand writting the yaml.

**Comment by ihuguet** [comment]
Maybe the same can work for interface, too.

Apart from that LGTM.

**Comment by cathay4t** [comment]
> Maybe the same can work for interface, too.

We already shipped support of this:

```yml
---
interfaces:
  - name: wan0
    type: ethernet
    state: up
    identifier: mac-address
    mac-address: 00:23:45:67:89:1a
```

> 
> Apart from that LGTM.

**Comment by ihuguet** [comment]
No, I mean to asume an implicit `identifier: mac-address` if `name` is omitted:
```
---
interfaces:
  - type: ethernet
    state: up
    mac-address: 00:23:45:67:89:1a
```

**Comment by cathay4t** [comment]
Unless certain use case require so, I prefer [`PEP-20: Explicit is better than implicit`][pep20_url]



[pep20_url]: https://peps.python.org/pep-0020/

**Comment by ihuguet** [comment]
User's desire is totally explicit: he/she wants to match by mac-address. Forcing the user to specify `identifier` is not being explicit, it's being redundant, and potentially confusing and easy to forget.

We need to specify `identifier` to support a different use case (nmstatectl show | apply), but that doesn't mean that all use cases should need it.

**Comment by cathay4t** [comment]
Having `identifier: mac-address` or not is cosmetic and can be easily accomplished in the future when needed without breaking API. But my option on this is __explicit__ instead of hidden default. 

I would suggest we move on.

**Comment by ihuguet** [comment]
As I already said, it's not only cosmetic, in my opinion:

> it's being redundant, and potentially confusing and easy to forget

If reviewer and reviewed doesn't agree on something, I suggest seeking for other's opinion in order to move forward.

**Comment by ffmancera** [comment]
All right, I have been thinking about this for a while and have some opinions. Maybe I am changing it too much and feel free to reject it. What about this?

```
    interfaces:
    - name: bond0
      type: bond
      state: up
      link-aggregation:
        mode: balance-rr
        ports-config:
        - identifier:
            method: mac-address
          mac-address: 00:23:45:67:89:1a
          iface-type: ethernet
        - identifier:
            method: mac-address
          mac-address: 00:23:45:67:89:1b
          iface-type: ethernet
```

If the `identifier` section is not present we can assume the user wants to match by name. Also this schema is easy to extend as we can add more fields under the `identifier` section in the future.

**Comment by ffmancera** [comment]
About the comments above: I agree that implicitly matching by MAC or Name depending on which one is present seems more elegant, but also I feel that we must document it really clear. Otherwise, users will be confused about it. I feel we have the same issue with IPv4 parameters where we implicitly set some defaults and users always have questions about them.

**Comment by ffmancera** [comment]
I would also like to weight in @tyll opinion, as he usually have nice insights about the schema.

**Comment by cathay4t** [comment]
> About the comments above: I agree that implicitly matching by MAC or Name depending on which one is present seems more elegant, but also I feel that we must document it really clear. Otherwise, users will be confused about it. I feel we have the same issue with IPv4 parameters where we implicitly set some defaults and users always have questions about them.

The problem is not for applying but querying: For example, when referring port via MAC, we should also include port name and MAC address in the query states, without identifier, we get different results when user apply this queried state back.

**Comment by cathay4t** [comment]
It should be a syntax sugar for applying that we automatically set port `identifier`, but for schema, we should be explicit.

And I do not like this syntax sugar as it does not save a lot typing and user have to read document to understand it.

I incline to make nmstate schema self-explained, not based on hidden defaults in 1000+ pages of document.

**Comment by cathay4t** [comment]
@ffmancera Thanks for the suggestion! I have amend it base on your suggestion.

**Comment by tyll** [comment]
According to https://nmstate.io/devel/yaml_api.html#bond-interface ports are matched with a `port` section which is a list of interface names. How does `ports-config` relate to this? I would like to see more examples about the expected behavior with the state of the system, the possible new states that can be defined and the expected outcomes.

Regarding deducting the users intent from whether name or mac-address is specified, this might only work good when the bond is created but create ambiguity when the bond is modified.

With a broader perspective, it seems it would be better to generally differ between the configured state (for example by matching based on mac addresses) and the runtime state (which is only reporting the state for interfaces by name). Then nmpolicy could be the configured state and be persisted (thinking about NM2) and allow potential complexity with matching. The actual runtime state would be the simple nmstate format.

**Comment by cathay4t** [comment]
> According to https://nmstate.io/devel/yaml_api.html#bond-interface ports are matched with a `port` section which is a list of interface names. How does `ports-config` relate to this? I would like to see more examples about the expected behavior with the state of the system, the possible new states that can be defined and the expected outcomes.

We cannot break schema for bond on `port` and `ports` accepting list of string as port names. So we introduce new section named `ports-config` section accepting dict/hashmap for bond and VRF. For bridge, existing `port` already accepting dict/hashmap. The `ports-config` taks priority over `port`.

More examples included.

> 
> Regarding deducting the users intent from whether name or mac-address is specified, this might only work good when the bond is created but create ambiguity when the bond is modified.

Could you elaborate this `ambiguity`?

> 
> With a broader perspective, it seems it would be better to generally differ between the configured state (for example by matching based on mac addresses) and the runtime state (which is only reporting the state for interfaces by name). Then nmpolicy could be the configured state and be persisted (thinking about NM2) and allow potential complexity with matching. The actual runtime state would be the simple nmstate format.

We cannot tell whether nmpolicy is idempotent or not, some of them cannot be persisted(otherwise it will alter changes done after this policy).
Nmstate already has `nmstatectl show --running-config` to include config only.

**Comment by tyll** [comment]
Does this meant that the `port` setting will be deprecated as part of this? It seems that Nmstate is now in a state that it needs to have a procedure to cleanup its API to avoid the situation that we have in NM with new methods being added to change the arguments without ever removing old API.

> More examples included.

Thanks. Could you include examples for the full lifecycle such as creating, modifying, removing and by name, by mac and mixed?

> Could you elaborate this ambiguity?

The current examples only show creating new interfaces with attached ports. There could be issues when changing the ports of an existing controller and also moving from MAC based to name based.

> We cannot tell whether nmpolicy is idempotent or not, some of them cannot be persisted(otherwise it will alter changes done after this policy).

This will probably require its own service that reads nmpolicy at boot and then configures networking instead of relying on NM.

> Nmstate already has nmstatectl show --running-config to include config only.

If this is the runtime state, will this show the new ports-config as well?

**Comment by cathay4t** [comment]
> Does this meant that the `port` setting will be deprecated as part of this? It seems that Nmstate is now in a state that it needs to have a procedure to cleanup its API to avoid the situation that we have in NM with new methods being added to change the arguments without ever removing old API.

I would consider `port` as simplify version on creating bond with ports.
We can deprecated it but will not able to remove it within 10 years as a lot customers are using it.
So this deprecation does not actually clean the API.

We may introduce `schema-version: 3` in YAML top level to indicate new YAML schema, and remove the support of YAML without `schema-version` in nmstate 3.x branch.

But this would require carefully planned in another issue.
> 
> > More examples included.
> 
> Thanks. Could you include examples for the full lifecycle such as creating, modifying, removing and by name, by mac and mixed?

The ports settings does not support partial editing, whenever user want to modify ports, they have to provide us full information. So creating, modifying and deletion ports are the same YAML.

> 
> > Could you elaborate this ambiguity?
> 
> The current examples only show creating new interfaces with attached ports. There could be issues when changing the ports of an existing controller and also moving from MAC based to name based.

Like above, we override port configures if defined by YAML.

> 
> > We cannot tell whether nmpolicy is idempotent or not, some of them cannot be persisted(otherwise it will alter changes done after this policy).
> 
> This will probably require its own service that reads nmpolicy at boot and then configures networking instead of relying on NM.

The policy is supported by `nmstate.service`, on service start, it convert policy into state by using current state, then apply to network backend(NM) as persistent. After applied, this policy YAML will be renamed to prevent repeat apply on next start of `nmstate.service`.

The `nmstate.service` is one shot service(run and then exit).

> 
> > Nmstate already has nmstatectl show --running-config to include config only.
> 
> If this is the runtime state, will this show the new ports-config as well?

Yes. `nmstatectl show --running-config` only remove running state from full query state, and this `ports-config` is not in the remove list.

**Comment by ihuguet** [comment]
I don't understand very well the benefit of this new `identifier` dict. What is the benefit compared to the previous proposal? What content will it shown with `nmstatectl show`?
About the cons: it is less intuitive and difficult to remember unless the user checks the docs or examples. It is also different from the current `interfaces.indentifier`, so the user will need to remember how it is done for interfaces and for ports.

**Comment by cathay4t** [comment]
> I don't understand very well the benefit of this new `identifier` dict. What is the benefit compared to the previous proposal? What content will it shown with `nmstatectl show`? 

Using `dict` allow us to expand to more options like `pci-slot-address`. If a port is mac identifier, both interface name and `identifier` section will be included in `nmstatectl show`. The `name` will be ignored when apply along with `identifier` section.

> About the cons: it is less intuitive and difficult to remember unless the user checks the docs or examples. It is also different from the current `interfaces.indentifier`, so the user will need to remember how it is done for interfaces and for ports.

I was hoping we could reuse this section at interface level to allow more matching methods in the future like PCI address.

**Comment by ihuguet** [comment]
And what `identifier` will appear in `nmstatectl show` if we match by name? And what `identifier` will be used to match by name?

> The name will be ignored when apply along with identifier section.

Hmm, it's not very intuitive that a field is ignored, but I guess that it's justified and can be documented.

BTW, maybe a better name like `match` can be used instead of `identifier`?

**Comment by cathay4t** [comment]
The identifier section will _not_ be included in `nmstatectl show` if match by name. We can add a syntax sugar for name matching so we could be consistent:

```yml
match:
  name: eth1
```

We can verify port name when both name and identifier section define.

I like `match` as it save some typing.

**Comment by cathay4t** [comment]
Schema updated to use `match` section.

**Comment by ihuguet** [comment]
Looks nice.

I have a question: what happens if a user specify "match by MAC", but it also set a new value for the MAC? Will there be any problem? Or is it solved by the "match by permanent MAC first" policy?

About this:
> I would consider port as simplify version on creating bond with ports.
We can deprecated it but will not able to remove it within 10 years as a lot customers are using it.
So this deprecation does not actually clean the API.

Why don't we convert `ports` to `ports-config`? Then, when we dump the current state, we only show `ports-config` because `ports` is deprecated.

**Comment by cathay4t** [comment]
> Looks nice.
> 
> I have a question: what happens if a user specify "match by MAC", but it also set a new value for the MAC? Will there be any problem? Or is it solved by the "match by permanent MAC first" policy?

Permanent MAC preferred, and fallback to bond port MAC address(MAC address before attaching bond).

For changing MAC at the same time using mac address identifier, we do not support such use case, but 
it might looks like this(unrelated to this issue, just showing this `match` section can be reused in interface level):

```yml
---
interfaces:
  - name: wan0
    type: ethernet
    state: up
    mac-address: 00:23:45:67:89:1b
  match:
    mac-address: 00:23:45:67:89:1a
    iface-type: ethernet
```

> 
> About this:
> 
> > I would consider port as simplify version on creating bond with ports.
> > We can deprecated it but will not able to remove it within 10 years as a lot customers are using it.
> > So this deprecation does not actually clean the API.
> 
> Why don't we convert `ports` to `ports-config`? Then, when we dump the current state, we only show `ports-config` because `ports` is deprecated.

Query output schema is also API, people might depend on old section name, so we can not remove old section.
