### ISSUE TITLE
The `gen_diff()` is not working for bridge vlan filtering

### ISSUE THREAD

**Issue by cathay4t** [nmstate/nmstate#2742]
Similar to https://issues.redhat.com/browse/RHEL-38623

```yml
---
interfaces:
  - name: br0
    type: linux-bridge
    state: up
    bridge:
      port:
        - name: eth1
          vlan:
            trunk-tags:
            - id-range:
                min: 3
                max: 4096
```

We should include port name as mandatory property in `gen_diff()` data.
