### ISSUE TITLE
[RFE] Support setting VLAN to bridge itself

### ISSUE THREAD

**Issue by Laikulo** [nmstate/nmstate#2769]
## Nmstate version
nmstatectl 2.2.35

## NetworkManager version
 1.42.4

## Platform
Armbian Bookworm

## How reproducible
100% (logical)

## Steps to Reproduce
It is not possible to express adding vlans to the self port of a linux-bridge interface.

## Nmstate output
- Expected output:
N/A
- Current output:
N/A

### Additional context
While the `nm_dbus` component supports setting vlans on the self port  
https://github.com/nmstate/nmstate/blob/a705ba4bf28686e1e6fab3b9b69f7f18f7558407/rust/src/lib/nm/nm_dbus/connection/bridge.rs#L60
https://github.com/nmstate/nmstate/blob/a705ba4bf28686e1e6fab3b9b69f7f18f7558407/rust/src/lib/nm/nm_dbus/gen_conf/bridge.rs#L28
The `linux-bridge` structure lacks a way to configure this, so it is not currently possible to use nmstate to configure a situation where a vlan-aware bridge has vlan interfaces on the host.

**Comment by cathay4t** [comment]
@Laikulo Are you expecting something like:

```yml
---
interfaces:
- name: br0
  type: linux-bridge
  state: up
  bridge:
    vlan:
      mode: access
      trunk-tags: []
      tag: 305
    port:
      - name: eth1
        vlan:
          mode: trunk
          trunk-tags:
          - id: 500
```

**Comment by Laikulo** [comment]
> @Laikulo Are you expecting something like:

Something like that would work well for me.

**Comment by Hoeze** [comment]
I would like to add a use case and a related request:

Please add the self port `vlan` section as proposed above, and let it count as a reason to enable VLAN filtering. 
Please also add an explicit `bridge.options.vlan-filtering`. Today a bridge cannot have filtering on while every port only uses the default PVID.

### Motivation

Host traffic uses the self port of a Linux bridge. This includes an IP on the bridge itself, and interfaces stacked on top of it, for example VLAN, macvlan or macvtap interfaces with the bridge as base interface. With VLAN filtering, the VLAN membership of the self port decides which VLANs reach the host on that path. NetworkManager supports this with `bridge.vlan-filtering` and `bridge.vlans` on the bridge profile. nmstate exposes neither of them.

### Why the self port section alone is not enough

nmstate derives `vlan-filtering` from the port `vlan` sections in [`gen_nm_br_setting()`](https://github.com/nmstate/nmstate/blob/70fa58c95bb80ff0e619e74f06d225948cd89fe2/rust/src/lib/nm/settings/bridge.rs#L29-L32):

```rust
if br_conf.port.is_some() {
    nm_br_set.vlan_filtering =
        Some(merged_br_iface.vlan_filtering_is_enabled());
}
```

[`vlan_filtering_is_enabled()`](https://github.com/nmstate/nmstate/blob/70fa58c95bb80ff0e619e74f06d225948cd89fe2/rust/src/lib/ifaces/linux_bridge.rs#L223-L236) returns true only if a port has a non-empty `vlan` section. When nmstate reads the current state, [`parse_port_vlan_conf()`](https://github.com/nmstate/nmstate/blob/70fa58c95bb80ff0e619e74f06d225948cd89fe2/rust/src/lib/nispor/linux_bridge_port_vlan.rs#L23-L25) skips the default PVID. From reading the code, this has two consequences:

1. A bridge with filtering on, where every port only uses the default PVID, reads back as "no VLAN config". The next apply with a port list turns filtering off again. A `bridge.vlan-filtering` set in the NetworkManager profile outside nmstate is overwritten the same way.
2. Enabling filtering requires at least one port VLAN that differs from the default PVID. This also holds when only the self port should be restricted.

### Proposal

```yaml
interfaces:
  - name: br0
    type: linux-bridge
    state: up
    bridge:
      options:
        vlan-filtering: true
      port:
        - name: eth1
        - name: eth2
```

With this, filtering is on, and every port as well as the self port only carries the default PVID untagged. Tagged frames no longer reach the host through the self port.

Suggested semantics:

- `vlan-filtering` unset: keep today's behavior, derived from the `vlan` sections. A self port `vlan` section should count as well.
- `vlan-filtering: true`: filtering is on, even without any `vlan` section.
- `vlan-filtering: false` together with a non-empty `vlan` section: validation error.
