### ISSUE TITLE
[Schema] Referring Parent base interface via MAC address

### ISSUE THREAD

**Issue by cathay4t** [nmstate/nmstate#2772]
For referring the parent base interface in VLAN/VxLAN/MacSec/MacVtap/MacVlan
via MAC address, we introduced these properties:

 * `base-iface-identifier`: `name` or `mac-address`, indicate whether parent is
   selected by interface name or MAC address.
 * `base-iface-mac-address`: MAC address of parent.
   Ignored when `base-iface-identifier: name`.
 * `base-iface-type`: interface type of parent. Please defined it when multiple
   interface is holding the same MAC address when using with
   `base-iface-identifier: mac-address`.

For example, to create a VLAN over interface holding MAC address
`00:23:45:67:89:1a`:

```yml
---
interfaces:
---
interfaces:
  - name: vlan101
    type: vlan
    state: up
    vlan:
      id: 101
      base-iface-identifier: mac-address
      base-iface-mac-address: 00:23:45:67:89:1a
      base-iface-type: ethernet
```

**Comment by ihuguet** [comment]
Except for the same concern of making `base-iface-identifier` mandatory or not, the rest LGTM.

**Comment by cathay4t** [comment]
This issue has been fixed, this is the schema we decided to use:

```
---
interfaces:
  - name: port1
    type: ethernet
    identifier: mac-address
    mac-address: 00:23:45:67:89:1a
  - name: vlan101
    type: vlan
    state: up
    vlan:
      base-iface: port1
      id: 101
```
