### ISSUE TITLE
Feature Request: bond option advmss

### ISSUE THREAD

**Issue by iamfaad** [nmstate/nmstate#2881]
Hi Team,
I have two openshift clusters across two DCs, openshift clusters are deployed with jumbo frames (9000mtu) however the path inbetween doesnot support jumbo and support 1500mtu only.
I am using separate vlan to for the communication between these two clusters for which i am specifying routes via nmstate nncp, however i do not see any option avaiable to define the mtu in nmstate nncp.
Can team please add these options so i can manage all routes through nncp only instead of defining it via nmcli or by creating machineconfig which will result in mcp rollout whenever i needed to add any new route.

**Comment by cathay4t** [comment]
The MTU of route is supported since 2.2.42+.

We need to code out the support of `advmss`, but it should be very simple.

**Comment by iamfaad** [comment]
Below is the available/supported configuration 
```
apiVersion: nmstate.io/v1
kind: NodeNetworkConfigurationPolicy
metadata:
  name: $nncp_name
spec:
  nodeSelector:
    node-role.kubernetes.io/worker: ""
  desiredState: 
   routes:
     config: 
     - destination: 10.21.x.x/24
       next-hop-address: 10.x.x.1
       next-hop-interface: bond0.101
       metric: 400
```

however i am requesting for configuration which supports mtu or advmss option as well as under;

```
apiVersion: nmstate.io/v1
kind: NodeNetworkConfigurationPolicy
metadata:
  name: $nncp_name
spec:
  nodeSelector:
    node-role.kubernetes.io/worker: ""
  desiredState: 
   routes:
     config: 
     - destination: 10.21.x.x/24
       next-hop-address: 10.x.x.1
       next-hop-interface: bond0.101
       metric: 400
       mtu: 1500    <------------ nncp to support this option.
       advmss: 1500 <------------ nncp to support this option.
```

Please support.
