### ISSUE TITLE
Bug report: command nmstatectl show stuck

### ISSUE THREAD

**Issue by fandz1979** [nmstate/nmstate#2897]
## Describe the bug
the command nmstatectl show is stuck in certain case

## Nmstate version
- Version 2.2.33

## NetworkManager version
- Version 1.42.2-21.el9_2

## Platform
- openshift / CoreOS 4.14

## How reproducible
- 100% when the condition is met

## Steps to Reproduce
When ovsdb response size is a multiple of 4096, the command will be stuck

## Nmstate output
- my configuration

- Current output: no output and process stuck

### Additional context
I think I've got a clue to the problem.

When running nmstatectl show -v, we see two messages:

```
DEBUG nmstate::ovsdb::json_rpc] OVSDB: sending command
DEBUG nmstate::ovsdb::json_rpc] OVSDB: recv data
```

And then nothing happens.

In cases where it doesn't block, we see:
```
DEBUG nmstate::ovsdb::json_rpc] OVSDB: sending command
DEBUG nmstate::ovsdb::json_rpc] OVSDB: recv data
DEBUG nmstate::ovsdb::json_rpc] OVSDB: recv string
```

In our case, we never see the recv string.
So, I looked at the source code and found the code related to the recv log.
It is the recv function in the following file rust/src/lib/ovsdb/json_rpc.rs (lines 57 to 98).

The logs OVSDB: recv data and OVSDB: recv string are in the same function, so this function is the one causing the issue.

I think the problem comes from the socket reception loop:
It is the block from lines 62 to 73:
```
loop {
    let mut buffer = [0u8; BUFFER_SIZE];
    let read = self
        .socket
        .read(&mut buffer)
        .map_err(parse_socket_io_error)?;
    log::debug!("OVSDB: recv data {:?}", &buffer[..read]);
    response.extend_from_slice(&buffer[..read]);
    if read < BUFFER_SIZE {
        break;
    }
}
```

There is an issue in this loop: the exit condition is that the amount of data received is less than the buffer size (here 4096). However, if the expected size is exactly 4096 or a multiple of 4096, the socket will wait for more data that it will never receive, and it will block.

I think this is the case here.
So, I ran an strace on the nmstatectl show command.
Here is what we see:
```
379712 recvfrom(9, "{\"error\"....,\"id\":1747899652}", 4096, 0, NULL, NULL) = 4096
2379712 recvfrom(9, 0x7ffc2acd24f0, 4096, 0, NULL, NULL) = ? ERESTARTSYS (To be restarted if SA_RESTART is set)
```

We receive a response of exactly 4096 bytes (the ,\"id\":1747899652} clearly marks the end of the request), but then it waits for more data on the socket that it will never receive.

I don't know Rust well enough to propose a solution, and besides, this function might be used elsewhere, so modifying it could affect other functions

**Comment by cathay4t** [comment]
We hit this problem in some rare cases, fantastic debug. Fixing is on the way.

**Comment by cathay4t** [comment]
Looks like JSON-RPC does not have EOM(end-of-message). I have to switch to tokio async unix stream using try_read. Stay tuned.

**Comment by cathay4t** [comment]
Reproduced this issue by YAML:

```
---
interfaces:
- name: ovs1
  type: ovs-interface
  state: up
  ovs-db:
    external_ids:
      a: 1
      b: 2
      c: 3
      d: 4
      f: 4
- name: br0
  type: ovs-bridge
  state: up
  bridge:
    port:
     - name: ovs1
     - name: ovs2
     - name: ovs3
     - name: ovs4
     - name: ovs5
     - name: ovs6
     - name: ovs7
     - name: ovs8
     - name: ovs9
     - name: ovs10
     - name: ovs11
     - name: ovs12
     - name: ovs13
     - name: ovs14
     - name: ovs15
     - name: ovs16
     - name: ovs17
```
