### ISSUE TITLE
It's not possible to create a bridge without routes

### ISSUE THREAD

**Issue by qinqon** [nmstate/nmstate#413]
With version 0.0.7

configuration

```yaml
interfaces: 
  - name: br1
    type: linux-bridge
    state: up
    bridge:
      options:
        stp:
          enabled: false
      port: 
        - name: eth0
          stp-hairpin-mode: false
          stp-path-cost: 100
          stp-priority: 32
```

result:

```yaml
desired
=======
---
routes:
- destination: 0.0.0.0/0
  metric: -1
  next-hop-address: 192.168.66.2
  next-hop-interface: eth0
  table-id: 0

current
=======
---
routes: []

difference
==========
--- desired
+++ current
@@ -1,7 +1,2 @@
 ---
-routes:
-- destination: 0.0.0.0/0
-  metric: -1
-  next-hop-address: 192.168.66.2
-  next-hop-interface: eth0
-  table-id: 0
+routes: []

```
