### ISSUE TITLE
Bridge's link stays in the system after setup fails with `device is strictly unmanaged`

### ISSUE THREAD

**Issue by phoracek** [nmstate/nmstate#516]
When a bridge setup fails, it successfully rolls back the NetworkManager connection, but the netlink device stays in the kernel:

```yaml
interfaces:
 - name: br4
   type: linux-bridge
   state: up
   bridge:
     options:
       stp:
         enabled: false
     port:
     - name: petr
```
-> Fails with `device is strictly unmanaged`

```
[root@t470s phoracek]# ip l | grep br4
20: br4: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UNKNOWN mode DEFAULT group default qlen 1000
[root@t470s phoracek]# nmcli c | grep br4
```

On top of that, nmstate is not able to remove the bridge in this state:

```yaml
interfaces:
- name: br4
  type: linux-bridge
  state: absent
```

-> Succeeds, br4 remains.

When I trigger the setup again, it fails due to non-existent port and cleans up the bridge.

https://paste.fedoraproject.org/paste/U-7cflqpwzFmyGT15WibCw

So I think we have two bugs here.

1. We are unable to rollback partially created interface
2. We have a race when creating virtual interfaces

We think we fixed the first one by applying the same workaround as is done for OVS interfaces - adding it to `remove_devs_actions`:

```diff
diff --git a/libnmstate/nm/applier.py b/libnmstate/nm/applier.py
index f67f948..09efb96 100644
--- a/libnmstate/nm/applier.py
+++ b/libnmstate/nm/applier.py
@@ -179,6 +179,7 @@ def set_ifaces_admin_state(ifaces_desired_state, con_profiles=()):
                         nmclient.NM.DeviceType.OVS_BRIDGE,
                         nmclient.NM.DeviceType.OVS_PORT,
                         nmclient.NM.DeviceType.OVS_INTERFACE,
+                        nmclient.NM.DeviceType.BRIDGE,
                     ):
                         remove_devs_actions[nmdev].append(device.delete_device)
             else:
```
