### ISSUE TITLE
Cannot set mac address manually on ovs-interface.

### ISSUE THREAD

**Issue by ormergi** [nmstate/nmstate#657]
When creating ovs-interface with NetworkManager there is an option to set the mac address through
 **802-3-ethernet.cloned-mac-address**, when combining it with **ipv4.method** set to **auto**
the ovs-interface managed to get the same ip address as the interface with mac address configured manually.
But when I try to create ovs-interface with nmstate its seems that there is no option to set the mac address manually.

'nmstate show' output after configuring with NetworkManager:

```
interfaces:
- name: mybr
  type: ovs-bridge
  state: up
  bridge:
    options:
      fail-mode: 
      mcast-snooping-enable: false
      rstp: false
      stp: false
    port:
    - name: eth1
    - name: mybr0
- name: mybr0
  type: ovs-interface
  state: up
  ipv4:
    address:
    - ip: 192.168.122.33
      prefix-length: 24
    auto-dns: true
    auto-gateway: true
    auto-routes: true
    dhcp: true
    enabled: true
  ipv6:
    address:
    - ip: fe80::5054:ff:fee0:647d
      prefix-length: 64
    auto-dns: true
    auto-gateway: true
    auto-routes: true
    autoconf: true
    dhcp: true
    enabled: true
  mtu: 1500
- name: eth1
  type: ethernet
  state: up
  ipv4:
    dhcp: false
    enabled: false
  ipv6:
    autoconf: false
    dhcp: false
    enabled: false
  mac-address: 52:54:00:E0:64:7D
  mtu: 1500
```
There is no representation to the mac address in ovs-bridge nor the ovs-interface.
