### ISSUE TITLE
Support for OVS bonding

### ISSUE THREAD

**Issue by ffmancera** [nmstate/nmstate#728]
As a user, I'd like to us nmstate to configure SLB bonding.

RFE: https://bugzilla.redhat.com/show_bug.cgi?id=1730341

## Proposed API

While OVS single interface port topology is:
```
Interface(eth0)-Port(eth0)-Bridge(br1)
```
For OVS bondings it is:
```
[Interface(eth0)+Interface(eth1)]-Port(bond1)-Bridge(br1)
```
Since bonds are just multiple Interfaces attached to a Port, I suggest we keep them under OVS bridge port. As a result, the API should be easy to read. If a user has a port that should have a vlan and be backed-up by multiple interfaces, this whole information should be visible in single state subtree.
```
name: br1
type: ovs-bridge
state: up
bridge:
  port:
  - name: bond1
    link-aggregation:
      mode: balance-slb
      slaves:
      - name: eth0
      - name: eth1
```
Single-slave bond is indistinguishable from system interface port, therefore at least 2 slaves are mandatory. 

## Current state

When there is a port attached to a bridge with multiple underlying interfaces, only one of them is shown.

Port with single iface
```
- name: bridge0
  type: ovs-bridge
  state: up
  bridge:
    options:
      fail-mode: ''
      mcast-snooping-enable: false
      rstp: false
      stp: false
    port:
    - name: v1a
      type: system
```
```
ff3015ae-ba93-48c7-8a43-d4f99399841c
    Bridge "bridge0"
        Port "bond0"
            Interface "v1a"
                type: system
    ovs_version: "2.10.1"
```
Port after attaching second iface
```
- name: bridge0
  type: ovs-bridge
  state: up
  bridge:
    options:
      fail-mode: ''
      mcast-snooping-enable: false
      rstp: false
      stp: false
    port:
    - name: v2a
      type: system
```
```
ff3015ae-ba93-48c7-8a43-d4f99399841c
    Bridge "bridge0"
        Port "bond0"
            Interface "v2a"
                type: system
            Interface "v1a"
                type: system
    ovs_version: "2.10.1"
```
## Links
https://github.com/nmstate/nmstate/pull/562
