### ISSUE TITLE
NM limits OVS port name

### ISSUE THREAD

**Issue by ffmancera** [nmstate/nmstate#730]
Following state
```
interfaces:
- name: a0123456
  state: up
  type: ovs-interface
- bridge:
    options:
      stp: true
    port:
    - name: a0123456
  name: ovs-br11
  state: up
  type: ovs-bridge
```
Fails with "onnection-error-quark: connection.interface-name: 'ovs-port-a0123456': interface name is longer than 15 characters".

There is no need to explicitly set connection.interface-name for OVS ports which are not represented by any interface. We should drop that in order to allow users to connect OVS Bridges to ports with names longer than 6 characters.
