### ISSUE TITLE
Repeat apply on fail_over_mac: "1" bond failed with NM_ACTIVE_CONNECTION_STATE_REASON_DEVICE_DISCONNECTED

### ISSUE THREAD

**Issue by cathay4t** [nmstate/nmstate#781]
2020-02-12 20:38:24,131 root         ERROR    NM main-loop aborted: Connection activation failed on bond99: reason=<enum NM_ACTIVE_CONNECTION_STATE_REASON_DEVICE_DISCONNECTED of type NM.ActiveConnectionStateReason>, <enum NM_DEVICE_STATE_FAILED of type NM.DeviceState> <enum NM_DEVICE_STATE_REASON_NONE of type NM.DeviceStateReason>

When applying this ymls repeatly(normally, second `set` will fail):

```yml
---
interfaces:
- name: eth1
  type: ethernet
  state: up
- name: bond99
  type: bond
  state: up
  link-aggregation:
    mode: active-backup
    slaves:
    - eth1
    options:
      fail_over_mac: "1"
```

https://bugzilla.redhat.com/show_bug.cgi?id=1801798
