### ISSUE TITLE
nmstatectl: Show propries in the insertion order.

### ISSUE THREAD

**Issue by tyll** [nmstate/nmstate#840]
nmstatectl should show the name of link-aggregration ports first in the output, for example:

```yaml
- name: ovs-br-lagg0
  type: ovs-bridge
  state: up
  bridge:
    port:
    - name: veth0_ep
    - name: ovs-lagg0
      link-aggregation:
        mode: balance-slb
        slaves:
        - name: veth1_ep
        - name: veth2_ep
```

This needs adjustments to order the state recursively (or at least specificially for ovs-bridges):
https://github.com/nmstate/nmstate/blob/master/libnmstate/prettystate.py#L91

**Comment by tyll** [comment]
If you fix this generically, it would be great to test it for team ports as well. But it could also be fixed in a different PR/issue if needed.

Example:

# cat team0.yaml 
```yaml
interfaces:
- name: team0
  type: team
  state: up
  team:
    ports:
    - name: vethteam0
    - name: vethteam0_ep
    runner:
      name: roundrobin
```

1. ip link add vethteam0 type veth peer name vethteam0_ep
nmcli dev set vethteam0 managed yes
nmcli dev set vethteam0_ep managed yes
2. nmstatectl set team0.yaml
3. nmstatectl show team0

Actual results:
```yaml
  team:
    - link_watch:
        name: ethtool
      name: vethteam0
    - link_watch:
        name: ethtool
      name: vethteam0_ep
    runner:
      name: roundrobin
```

Expected results:
```yaml
  team:
    ports:
    - name: vethteam0
      link_watch:
        name: ethtool
    - name: vethteam0_ep
      link_watch:
        name: ethtool
    runner:
      name: roundrobin
```
