### ISSUE TITLE
Multicast route lost in `libnmstate.show()` after rollback

### ISSUE THREAD

**Issue by cathay4t** [nmstate/nmstate#937]
The `ff00::/8` multicast route will lost after rollback.

```yaml
---
interfaces:
- name: dummy1
  type: dummy
  state: up
  ipv4:
    enabled: false
  ipv6:
    enabled: true
    dhcp: false
    autoconf: false
    address:
    - ip: 2001:db8:1::3
      prefix-length: 64
```

Then `nmstatectl show dummy1` has route to `ff00::/8`.

After:
```yaml
---
interfaces:
- name: dummy1
  type: dummy
  state: up
  mtu: 0
```

Then `nmstatectl show dummy1` does __not__ have route to `ff00::/8`.
