### ISSUE TITLE
nmstatectl: Properly sort the priorities

### ISSUE THREAD

**Issue by cathay4t** [nmstate/nmstate#940]
Currently, nmstatectl show OVS bond as:

```yml
    port:
    - name: veth0_ep
    - link-aggregation:
        mode: balance-slb
        slaves:
        - name: veth1_ep
        - name: veth2_ep
      name: ovs-lagg0
```

Expected:

```yml

    port:
    - name: veth0_ep
    - name: ovs-lagg0
      link-aggregation:
        mode: balance-slb
        slaves:
        - name: veth1_ep
        - name: veth2_ep
```
